#!/bin/bash

# instructions here: https://github.com/sickcodes/Docker-OSX#usbfluxd-iphone-usb---network-style-passthrough-osx-kvm-docker-osx

echo "This script should be run in the host, not the macOS VM. If you are running this script from the host, this message can be safely ignored."
sudo systemctl restart usbmuxd
sudo socat tcp-listen:5000,fork unix-connect:/var/run/usbmuxd
