#!/bin/sh

host_location=192.168.1.100

if [ "$1" != "" ]; then
  host_location="$1"
fi

echo "
This script should be run in the macOS VM, not the host. If you are running this script from the macOS VM, you can ignore this message.

---

Ensure that you have followed the instructions to set up usbfluxd in the macOS VM:

- Install Homebrew.

- Install required dependencies:
  - Via Homebrew:
    - brew install make automake autoconf libtool pkg-config gcc libimobiledevice usbmuxd
  - Build and install usbfluxd:

git clone https://github.com/corellium/usbfluxd.git
cd usbfluxd

./autogen.sh
make
sudo make install

---


Using host location: ${host_location}

Modify this script if your host is located elsewhere."


# # old code (may still be useful)
# sudo launchctl start usbmuxd
# export PATH=/usr/local/sbin:${PATH}
# sudo usbfluxd -f -r ${host_location}:5000

sudo usbfluxd -f -r ${host_location}:5000
